# Generated by Django 3.0 on 2019-12-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('yunta', '0004_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido_materno',
            field=models.CharField(default='a', max_length=150, verbose_name='Apellido materno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellido_paterno',
            field=models.CharField(default='a', max_length=150, verbose_name='Apellido paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='F', max_length=10, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default='a', max_length=150, verbose_name='Nombres'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
