# Generated by Django 3.0 on 2019-12-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunta', '0005_auto_20191211_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='nro_cuotas',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
