# Generated by Django 3.0 on 2019-12-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunta', '0006_junta_nro_cuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='junta',
            name='puja',
            field=models.IntegerField(default=0),
        ),
    ]
