# Generated by Django 3.0 on 2019-12-11 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yunta', '0007_auto_20191211_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monedero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_actual', models.IntegerField()),
                ('saldo_contable', models.IntegerField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monedero',
                'verbose_name_plural': 'Monederos',
                'ordering': ['-saldo_actual'],
            },
        ),
    ]
