# Generated by Django 3.0 on 2019-12-12 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yunta', '0009_auto_20191212_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='junta',
            old_name='nombre',
            new_name='name',
        ),
    ]
