# Generated by Django 3.0 on 2019-12-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunta', '0011_auto_20191212_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='abierto',
            field=models.BooleanField(default=False),
        ),
    ]
