# Generated by Django 3.0 on 2019-12-13 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('yunta', '0012_junta_abierto'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='nro_participantes',
            field=models.IntegerField(default=2),
        ),
        migrations.CreateModel(
            name='ParticipanteJunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('nro_cuotas', models.IntegerField()),
                ('cuota', models.IntegerField()),
                ('puja', models.IntegerField(default=0)),
                ('mi_puja', models.IntegerField(default=0)),
                ('fecha', models.CharField(max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('junta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yunta.Junta')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Junta',
                'verbose_name_plural': 'Juntas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleParticipanteJunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('nro_cuotas', models.IntegerField()),
                ('nro_cuota_actual', models.IntegerField()),
                ('cuota', models.IntegerField()),
                ('puja', models.IntegerField(default=0)),
                ('puja_actual', models.IntegerField(default=0)),
                ('fecha_pago', models.DateField(null=True)),
                ('esta_pagado', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('participante_junta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yunta.ParticipanteJunta')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Junta',
                'verbose_name_plural': 'Juntas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
