# Generated by Django 3.0 on 2019-12-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunta', '0014_participantejunta_es_creador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantejunta',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
