# Generated by Django 3.0 on 2019-12-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunta', '0016_auto_20191213_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantejunta',
            name='es_activo',
            field=models.BooleanField(default=True),
        ),
    ]
