# Generated by Django 3.0 on 2019-12-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunta', '0017_participantejunta_es_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantejunta',
            name='mi_cuota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='junta',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='junta',
            name='puja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='participantejunta',
            name='mi_puja',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='participantejunta',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
