# Generated by Django 3.0 on 2019-12-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yunta', '0018_auto_20191213_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='junta',
            name='iniciar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='participantejunta',
            name='iniciar',
            field=models.BooleanField(default=False),
        ),
    ]
